= 📖 Steadfast Self-Hosting, auf Deutsch
:hide-uri-scheme:

German translation of https://github.com/meonkeys/shb[Steadfast Self-Hosting].

== Translator notes

When it comes to L10n and i18n, we get whatever Asciidoctor provides.
Here are some conventions and caveats for future translators.

For quoting, use literal UTF-8 characters for typographic/curved double-quotes, e.g. `„richtigen“`.

For pauses, use literal UTF-8 en dash (U+2013) surrounded by spaces, e.g. `ins Internet – und wichtige`.

Date/time values are not localized.
Example: `Dieses Buch wurde am Tue May 27 11:39:42 AM PDT 2025 mit LANG auf Einstellung de_DE.UTF-8...`.

IMPORTANT: FIXME - translate the word "Colophon"

See also:

* https://docs.asciidoctor.org/asciidoctor/latest/localization-support/[localization in Asciidoctor manual]
* https://github.com/asciidoctor/asciidoctor/issues/1658[asciidoctor/asciidoctor issue #1658: Support internationalization and localisation]
* https://github.com/asciidoctor/asciidoctor/issues/1670[asciidoctor/asciidoctor issue #1670: Localization for curved quotes]
* https://github.com/meonkeys/shb/blob/main/issues.adoc[issues in English version], since those apply to translated versions as well

== 📜 Warranty

None.

== ⚖️ Copyright and license

The book is (C)2025 Adam Monsen. Some rights reserved. License is https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) License]. This notice also appears in `book/steadfast.asciidoc` and typeset outputs.

mario is (C)2023-2025 Adam Monsen. License is https://www.gnu.org/licenses/agpl-3.0.html[GNU Affero General Public License] as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This notice also appears in `mario/Readme.md` and source code.
